### ISSUE TITLE
SPF macros - DNS response includes invalid characters

### ISSUE THREAD

**Issue by niftylettuce** [andris9/mailauth#7]
```sh
 dig +short TXT officedepot.com | grep spf

"v=spf1 include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email ~all"
```

```sh
dig +short TXT 205.157.110.125._ip.odmailout01.officedepot.com._ehlo.officedepot.com._spf.vali.email

"v=spf1 ip4:205.157.110.125 -all"
```

It looks like macros aren't supported by this library or standard Node.js DNS lookups?

**Comment by niftylettuce** [comment]
`Received-SPF: permerror (mx2.forwardemail.net: permanent error in processing during lookup of ODOnline@OfficeDepot.com: DNS response includes invalid characters) client-ip=XXXXXXXX;`

**Comment by andris9** [comment]
Macros are supported and actually mailauth is able to resolve that IP as a valid SPF. There problem appears to be different - the result of TXT response includes a newline symbol here:

```
"google-site-verification=ATdlU_lGMOoWJvPUQErCQWflNikOvpIAuXRb7ZwpLqE\010"
```

Mailauth currently rejects TXT results because of that newline as it looks at the complete resolving result, not individual lines. I guess it should allow a better validation like skipping everything that is not SPF related and maybe replace all whitespace symbols, including newlines with regular spaces before validation.

**Comment by niftylettuce** [comment]
@andris9 that'd be awesome - can you patch this? I'll sponsor on GH again!

**Comment by andris9** [comment]
Could you try v2.1.3 if it works correctly for you?

**Comment by niftylettuce** [comment]
I just upgraded and pinged my customer to test
